TASK 1


In [6]:
parking_data=[
    {"id": "A01", "zone":"A", "status":"occupied", "rate":100},
    {"id": "A02", "zone":"A", "status":"available", "rate":100},
    {"id": "B01", "zone":"B", "status":"occupied", "rate":80},
    {"id": "B02", "zone":"B", "status":"available", "rate":80},
    {"id": "C01", "zone":"C", "status":"available", "rate":120},
    {"id": "C02", "zone":"C", "status":"occupied", "rate":120}
]

available=[s for s in parking_data if s["status"]=="available"]

for s in available:
 print(s["id"], s["zone"], s["status"], s["rate"])

zones = {slot["zone"] for slot in parking_data}

available_spaces=0
occupied_spaces=0

for s in parking_data:
    if(s["status"]=="available"):
        available_spaces+=1
    else:
        occupied_spaces+=1


print("Available: ", available_spaces)
print("Occupied: ", occupied_spaces)



def calculate_cost(rate, hours):
    return rate*hours

sorted_rates=sorted(available, key=lambda s: s["rate"])

hours_worked=int(input("How many hours do you wish to park for?"))

print("Estimated costs: ")
for slot in available:
    cost=calculate_cost(slot["rate"], hours_worked)
    print(f"Space {slot["id"]} (Zone {slot["zone"]}): Rs{cost}")

cheapest = min(available, key=lambda s: calculate_cost(s["rate"], hours_worked))
print(f"\nCheapest option: Space {cheapest['id']} (Zone {cheapest['zone']}) "
      f"at Rs {calculate_cost(cheapest['rate'], hours_worked)}")


A02 A available 100
B02 B available 80
C01 C available 120
Available:  3
Occupied:  3
Estimated costs: 
Space A02 (Zone A): Rs300
Space B02 (Zone B): Rs240
Space C01 (Zone C): Rs360

Cheapest option: Space B02 (Zone B) at Rs 240


TASK 2

In [ ]:
from functools import reduce

login_data = {
    "192.168.1.10": 3,
    "192.168.1.21": 17,
    "192.168.1.35": 5,
    "192.168.1.42": 24,
    "192.168.1.51": 11,
    "192.168.1.63": 2
}

suspicious_ips = list(filter(lambda item: item[1] > 10, login_data.items()))

risk_scores = list(map(lambda item: (item[0], item[1] * 2), suspicious_ips.items()))

total_risk_score = reduce(lambda acc, score: acc + score, risk_scores.values(), 0)

suspicious_set = set(suspicious_ips.keys())

highest_ip = max(suspicious_ips.items(), key=lambda item: item[1])

def classify_risk(attempts):
    if 11 <= attempts <= 15:
        return "Medium Risk"
    elif 16 <= attempts <= 20:
        return "High Risk"
    else:
        return "Critical Risk"

classified_ips = {ip: classify_risk(attempts) for ip, attempts in suspicious_ips.items()}

print("=== Security Report ===")
print("Suspicious IPs:", suspicious_set)
print("\nDetailed Risk Scores:")
for ip, score in risk_scores.items():
    print(f"{ip} -> Risk Score: {score}, Classification: {classified_ips[ip]}")

print(f"\nTotal Risk Score: {total_risk_score}")
print(f"Most Dangerous IP: {highest_ip[0]} with {highest_ip[1]} failed attempts ({classified_ips[highest_ip[0]]})")


=== Security Report ===
Suspicious IPs: {'192.168.1.21', '192.168.1.42', '192.168.1.51'}

Detailed Risk Scores:
192.168.1.21 -> Risk Score: 34, Classification: High Risk
192.168.1.42 -> Risk Score: 48, Classification: Critical Risk
192.168.1.51 -> Risk Score: 22, Classification: Medium Risk

Total Risk Score: 104
Most Dangerous IP: 192.168.1.42 with 24 failed attempts (Critical Risk)


TASK 3


In [8]:
import numpy as np

books = np.array([
    [4.5, 120, 80],
    [4.2, 200, 65],
    [4.8, 150, 95],
    [3.9, 300, 55],
    [4.6, 180, 88]
])

print("Shape:", books.shape)   
print("Size:", books.size)     
print("Data type:", books.dtype)

column_means = np.mean(books, axis=0)
print("\nMean values (Rating, Views, Popularity):", column_means)

min_vals = books.min(axis=0)
max_vals = books.max(axis=0)
normalized_books = (books - min_vals) / (max_vals - min_vals)
print("\nNormalized data:\n", normalized_books)

scores = 0.5 * normalized_books[:, 0] + 0.2 * normalized_books[:, 1] + 0.3 * normalized_books[:, 2]
print("\nRecommendation Scores:", scores)

ranking = np.argsort(scores)[::-1]  
print("\nRanking (best to worst):", ranking)


print("\nBook Rankings and Scores:")
for idx in ranking:
    print(f"Book {idx+1}: Score = {scores[idx]:.4f}")


best_book = ranking[0]
print(f"\nBest Book: Book {best_book+1} with Score = {scores[best_book]:.4f}")

ratings = books[:, 0]
popularity = books[:, 2]
print("\nRatings:", ratings)
print("Popularity:", popularity)


Shape: (5, 3)
Size: 15
Data type: float64

Mean values (Rating, Views, Popularity): [  4.4 190.   76.6]

Normalized data:
 [[0.66666667 0.         0.625     ]
 [0.33333333 0.44444444 0.25      ]
 [1.         0.16666667 1.        ]
 [0.         1.         0.        ]
 [0.77777778 0.33333333 0.825     ]]

Recommendation Scores: [0.52083333 0.33055556 0.83333333 0.2        0.70305556]

Ranking (best to worst): [2 4 0 1 3]

Book Rankings and Scores:
Book 3: Score = 0.8333
Book 5: Score = 0.7031
Book 1: Score = 0.5208
Book 2: Score = 0.3306
Book 4: Score = 0.2000

Best Book: Book 3 with Score = 0.8333

Ratings: [4.5 4.2 4.8 3.9 4.6]
Popularity: [80. 65. 95. 55. 88.]


TASK 4


In [9]:
import numpy as np

field_data = [
    {"field": "F1", "temperature": 34, "humidity": 55, "soil_moisture": 28},
    {"field": "F2", "temperature": 29, "humidity": 72, "soil_moisture": 61},
    {"field": "F3", "temperature": 38, "humidity": 48, "soil_moisture": 22},
    {"field": "F4", "temperature": 31, "humidity": 65, "soil_moisture": 47},
    {"field": "F5", "temperature": 36, "humidity": 50, "soil_moisture": 30}
]

irrigation_fields = [f["field"] for f in field_data if f["soil_moisture"] < 30]

heat_stress_fields = [f["field"] for f in field_data if f["temperature"] > 35]

critical_fields = [f["field"] for f in field_data if f["soil_moisture"] < 30 and f["temperature"] > 35]

print("Fields requiring irrigation:", irrigation_fields)
print("Fields under heat stress:", heat_stress_fields)
print("Critical fields (both conditions):", critical_fields)

matrix = np.array([[f["temperature"], f["humidity"], f["soil_moisture"]] for f in field_data])
print("\nSensor Matrix:\n", matrix)

means = matrix.mean(axis=0)
print("\nMean Temperature:", means[0])
print("Mean Humidity:", means[1])
print("Mean Soil Moisture:", means[2])

variances = matrix.var(axis=0)
print("\nVariance (Temp, Humidity, Soil Moisture):", variances)

sensors = ["Temperature", "Humidity", "Soil Moisture"]
highest_var_sensor = sensors[np.argmax(variances)]
print("Sensor with highest variance:", highest_var_sensor)

min_vals = matrix.min(axis=0)
max_vals = matrix.max(axis=0)
normalized = (matrix - min_vals) / (max_vals - min_vals)

scores = 0.4 * normalized[:, 0] + 0.2 * normalized[:, 1] + 0.4 * (1 - normalized[:, 2])

ranking = np.argsort(scores)[::-1]

print("\n=== Field Risk Report ===")
for idx in ranking:
    field = field_data[idx]["field"]
    score = scores[idx]
    if score > 0.7:
        status = "High Risk → Immediate inspection required"
    elif score > 0.4:
        status = "Medium Risk → Monitor field"
    else:
        status = "Low Risk → Normal condition"
    print(f"{field}: Risk Score = {score:.3f}, {status}")


Fields requiring irrigation: ['F1', 'F3']
Fields under heat stress: ['F3', 'F5']
Critical fields (both conditions): ['F3']

Sensor Matrix:
 [[34 55 28]
 [29 72 61]
 [38 48 22]
 [31 65 47]
 [36 50 30]]

Mean Temperature: 33.6
Mean Humidity: 58.0
Mean Soil Moisture: 37.6

Variance (Temp, Humidity, Soil Moisture): [ 10.64  83.6  205.84]
Sensor with highest variance: Soil Moisture

=== Field Risk Report ===
F3: Risk Score = 0.800, High Risk → Immediate inspection required
F5: Risk Score = 0.646, Medium Risk → Monitor field
F1: Risk Score = 0.619, Medium Risk → Monitor field
F4: Risk Score = 0.374, Low Risk → Normal condition
F2: Risk Score = 0.200, Low Risk → Normal condition


TASK 5


In [10]:
import numpy as np
import math

stops = [
    ("Stop A", (33.6425, 73.1730)),
    ("Stop B", (33.6500, 73.1600)),
    ("Stop C", (33.6550, 73.1500)),
    ("Stop D", (33.6600, 73.1400)),
    ("Stop E", (33.6650, 73.1300))
]

stop_dict = {name: coords for name, coords in stops}

visited_stops = set()

def has_visited(stop):
    return stop in visited_stops

def visit_stop(stop):
    if not has_visited(stop):
        visited_stops.add(stop)

routes = [
    ["Stop A", "Stop B", ["Stop C", "Stop D"]],
    ["Stop A", ["Stop E"]]
]

def flatten_routes(route):
    flat = []
    for r in route:
        if isinstance(r, list):
            flat.extend(flatten_routes(r))  
        else:
            flat.append(r)
    return flat

flattened_route = flatten_routes(routes)

for stop in flattened_route:
    visit_stop(stop)

def calculate_distance(point1, point2):
    return math.sqrt((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)

coords_array = np.array([coords for _, coords in stops])

mean_lat = np.mean(coords_array[:, 0])
mean_lon = np.mean(coords_array[:, 1])
min_lat = np.min(coords_array[:, 0])
max_lat = np.max(coords_array[:, 0])

distances = []
for i in range(len(flattened_route) - 1):
    p1 = stop_dict[flattened_route[i]]
    p2 = stop_dict[flattened_route[i+1]]
    d = calculate_distance(p1, p2)
    distances.append((flattened_route[i], flattened_route[i+1], d))

closest_pair = min(distances, key=lambda x: x[2])

print("=== Intelligent Public Transport Route Analyzer ===")
print("\nFlattened Route:", flattened_route)
print("Visited Stops:", visited_stops)

print("\nRoute Statistics:")
print(f"Mean Latitude: {mean_lat:.4f}")
print(f"Mean Longitude: {mean_lon:.4f}")
print(f"Min Latitude: {min_lat:.4f}")
print(f"Max Latitude: {max_lat:.4f}")

print("\nDistances Between Consecutive Stops:")
for s1, s2, d in distances:
    print(f"{s1} → {s2}: {d:.4f}")

print(f"\nClosest Pair of Consecutive Stops: {closest_pair[0]} → {closest_pair[1]} ({closest_pair[2]:.4f})")


=== Intelligent Public Transport Route Analyzer ===

Flattened Route: ['Stop A', 'Stop B', 'Stop C', 'Stop D', 'Stop A', 'Stop E']
Visited Stops: {'Stop B', 'Stop A', 'Stop E', 'Stop D', 'Stop C'}

Route Statistics:
Mean Latitude: 33.6545
Mean Longitude: 73.1506
Min Latitude: 33.6425
Max Latitude: 33.6650

Distances Between Consecutive Stops:
Stop A → Stop B: 0.0150
Stop B → Stop C: 0.0112
Stop C → Stop D: 0.0112
Stop D → Stop A: 0.0374
Stop A → Stop E: 0.0485

Closest Pair of Consecutive Stops: Stop B → Stop C (0.0112)
